import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')

serve(async (req) => {
    // 1. Handle CORS
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: { 'Access-Control-Allow-Origin': '*' } })
    }

    try {
        const payload = await req.json()
        const { user, email_data } = payload

        if (!user || !user.email) {
            throw new Error("Invalid payload: missing user email")
        }

        const { email_action_type, token, token_hash, redirect_to, site_url, token_new, token_hash_new } = email_data

        // We build the Auth URL mimicking Supabase's default behavior.
        // SUPABASE_URL is automatically injected into Edge Functions by Supabase.
        const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? site_url
        // ensure redirect_to is encoded if it exists
        const redirectParam = redirect_to ? `&redirect_to=${encodeURIComponent(redirect_to)}` : ''

        const confirmationUrl = `${supabaseUrl}/auth/v1/verify?token=${token_hash}&type=${email_action_type}${redirectParam}`
        const confirmationUrlNew = `${supabaseUrl}/auth/v1/verify?token=${token_hash_new}&type=${email_action_type}${redirectParam}`

        let subject = 'Notification from our app'
        let html = `<p>Action: ${email_action_type}</p><p>Token: ${token}</p>`

        switch (email_action_type) {
            case 'signup':
                subject = 'Confirm your signup'
                html = `<h2>Welcome!</h2><p>Please confirm your email by clicking the link below:</p><p><a href="${confirmationUrl}">Confirm Email</a></p><p>Alternatively, enter this code manually: <strong>${token}</strong></p>`
                break
            case 'magiclink':
                subject = 'Log in with this Magic Link'
                html = `<h2>Log into your account</h2><p>Click the link below to get logged in:</p><p><a href="${confirmationUrl}">Log In</a></p><p>Alternatively, enter this code manually: <strong>${token}</strong></p>`
                break
            case 'recovery':
                subject = 'Reset Your Password'
                html = `<h2>Password Reset Request</h2><p>Click the link below to securely reset your password:</p><p><a href="${confirmationUrl}">Reset Password</a></p><p>Alternatively, enter this code manually: <strong>${token}</strong></p>`
                break
            case 'invite':
                subject = 'You have been invited'
                html = `<h2>You're invited!</h2><p>Click the link below to accept your invitation:</p><p><a href="${confirmationUrl}">Accept Invite</a></p>`
                break
            case 'email_change':
                subject = 'Confirm Email Change'
                html = `<h2>Email Change Request</h2><p>You requested an email change. Confirm it here:</p><p><a href="${confirmationUrlNew}">Confirm New Email</a></p><p>Alternatively, enter this code manually: <strong>${token_new}</strong></p>`
                break
        }

        // 2. Call Resend API
        const resendPayload: any = {
            from: 'Auth <onboarding@resend.dev>', // UPDATE THIS to your verified domain in Resend
            to: [user.email],
            subject: subject,
        }

        if (email_action_type === 'signup') {
            resendPayload.template_id = 'confirm-signup' // Specific ID provided by user

            // In Resend, template variables are passed alongside the template_id via the 'react' property or by injecting data into an object,
            // however standard HTTP 'id' based templates from the dashboard accept variables via the `headers` or custom JSON structure depending on the setup. 
            // The standard way Resend accepts dynamic variables for React Email templates via API when using a plain template ID is via the `tags` or `headers` object, or by injecting it straight into the payload root if supported by the template designer.
            // Often, it's easier to use the `react` property with the compiled component, or the `headers` property for custom variables.
            // *Wait, according to Resend API v2 for Templates (via ID)*: You can pass an object called `dynamic_template_data` or simply add variables as root properties? Actually, Resend uses React Email. If you're using a Template ID built in their dashboard, they don't natively support dynamic variables via API in the same way SendGrid does through `dynamic_template_data`. The recommended way on Resend is to send the `html` generated by `render()` from `@react-email`, BUT if they have a Template ID, maybe it's purely static, or we need to pass a context object. 
            // Wait, looking at Resend Documentation: Resend doesn't natively support Handlebars `{{ }}` for templates built via their React editor hosted on their dashboard if you call it via template_id without sending `html`. 
            // Let's pass the URL just in case they are parsing it using a custom header or string replacement in their own client.

            // To be safe and broadly compatible, I will assign the dynamic variables in the payload as `tags` which is natively supported. If their template uses something else, they can modify this object.

            resendPayload.tags = [
                { name: 'confirmationUrl', value: confirmationUrl },
                { name: 'token', value: token }
            ]

            resendPayload.text = `Welcome! Confirm here: ${confirmationUrl}` // Fallback text
        } else {
            resendPayload.html = html
        }

        const res = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${RESEND_API_KEY}`,
            },
            body: JSON.stringify(resendPayload),
        })

        if (!res.ok) {
            const errorData = await res.text()
            throw new Error(`Resend API error: ${errorData}`)
        }

        const data = await res.json()
        return new Response(JSON.stringify(data), {
            status: 200,
            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
        })

    } catch (error: unknown) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred'
        return new Response(JSON.stringify({ error: errorMessage }), {
            status: 500,
            headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
        })
    }
})
